spring:
  datasource:
     url: jdbc:mysql://localhost:3306/activiti?useUnidcoe=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=UTC
     username: root
     password: 123
     driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true